### ISSUE TITLE
.PS not included in the error message with THAT

### ISSUE THREAD

**Issue by vduong143** [genelkim/ulf-sanity-checker#15]
************************************
## Sanity checking formula (before preprocessing).
```
((YOU.PRO ((PRES SHOULD.AUX-V) (STUDY.V HARD.ADV-A)))
 (SO_THAT.PS (YOU ((PRES CAN.AUX-S) (PASS.V (THE.D EXAMINATION.N))))))
```

## Sanity checking formula (after preprocessing).
```
(((YOU.PRO ((PRES SHOULD.AUX-V) (STUDY.V HARD.ADV-A)))
  (SO_THAT.PS (YOU ((PRES CAN.AUX-S) (PASS.V (THE.D EXAMINATION.N))))))
 NIL NIL)
```

## Possible errors

Possibly failed conditions:
  _"that/tht/whether/ans-to take a single tensed sentence argument."_
Ann segment:
  ```
(SO_THAT.PS (YOU ((PRES CAN.AUX-S) (PASS.V (THE.D EXAMINATION.N)))))
```
Predicted constituent types ((list of types) -- constituent)
  ```
((UNKNOWN) -- SO_THAT.PS)
```
  ```
((UNKNOWN) -- (YOU ((PRES CAN.AUX-S) (PASS.V (THE.D EXAMINATION.N)))))
```

Possibly failed conditions:
  _"UNKNOWN detected in type analysis.  Please ensure this isn't from an annotation error."_
Ann segment:
  ```
NIL
```
Predicted constituent types ((list of types) -- constituent)

## Formula with predicted types (for debugging).

```
(((TYPES UNKNOWN)
  (((TYPES TENSED-SENT)
    (YOU.PRO
     ((TYPES PRED TENSED-VERB)
      (((TYPES TENSED-AUX) (PRES SHOULD.AUX-V))
       ((TYPES VERB PRED) (STUDY.V HARD.ADV-A))))))
   ((TYPES UNKNOWN)
    (SO_THAT.PS
     ((TYPES UNKNOWN)
      (YOU
       ((TYPES PRED TENSED-VERB)
        (((TYPES TENSED-AUX) (PRES CAN.AUX-S))
         ((TYPES VERB PRED)
          (PASS.V ((TYPES TERM) (THE.D EXAMINATION.N)))))))))))))
```

NIL

####################################

**Comment by genelkim** [comment]
*.ps is of the same type as `that`, `ans-to`, etc. That is, *.ps requires its arguments to be tensed sentences. The issue here seems to be that `you` should be `you.pro`. Without it, the sentence type is not properly analyzed.
