### ISSUE TITLE
Sanity checker fails on inverted be.v

### ISSUE THREAD

**Issue by genelkim** [genelkim/ulf-sanity-checker#2]
************************************
Sanity checking formula (before preprocessing).
************************************
(((PRES BE.V) YOU.PRO (CONCERNED.A (WITH.P-ARG (K (PLUR POLITIC.N)))))
 ?)

************************************
Sanity checking formula (after preprocessing).
************************************
((((PRES BE.V) YOU.PRO (CONCERNED.A (WITH.P-ARG (K (PLUR POLITIC.N)))))
  ?)
 NIL NIL)

************************************
Possible errors
************************************

Possibly failed conditions:
  "Sentence punctuation takes a single tensed sentence argument and is post-fixed."
Ann segment:
  (((PRES BE.V) YOU.PRO
    (CONCERNED.A (WITH.P-ARG (K (PLUR POLITIC.N)))))
   ?)
Predicted constituent types ((list of types) -- constituent)
  ((PRED TENSED-VERB) --
   ((PRES BE.V) YOU.PRO
    (CONCERNED.A (WITH.P-ARG (K (PLUR POLITIC.N))))))
  ((SENT-PUNCT) -- ?)

Possibly failed conditions:
  "be.v takes a single predicate argument (unless used after an it-cleft -- ignore this if that's the case)."
Ann segment:
  ((PRES BE.V) YOU.PRO (CONCERNED.A (WITH.P-ARG (K (PLUR POLITIC.N)))))
Predicted constituent types ((list of types) -- constituent)
  ((PRED TENSED-VERB) -- (PRES BE.V))
  ((TERM) -- YOU.PRO)
  ((ADJ PRED) -- (CONCERNED.A (WITH.P-ARG (K (PLUR POLITIC.N)))))

Possibly failed conditions:
  "UNKNOWN detected in type analysis.  Please ensure this isn't from an annotation error."
Ann segment:
  NIL
Predicted constituent types ((list of types) -- constituent)

************************************
Formula with predicted types (for debugging).
************************************
(((TYPES UNKNOWN)
  (((TYPES PRED TENSED-VERB)
    (((TYPES PRED TENSED-VERB) (PRES BE.V)) YOU.PRO
     ((TYPES ADJ PRED)
      (CONCERNED.A
       ((TYPES P-ARG)
        (WITH.P-ARG
         ((TYPES TERM) (K ((TYPES NOUN PRED) (PLUR POLITIC.N))))))))))
   ?))
 NIL NIL)

NIL

###################################

**Comment by vduong143** [comment]
Sid: 228800
"Are you sure of your facts?"
(((pres be.v) you.pro (sure.a (of.p-arg (your.d (plur fact.n)))))?)

**Comment by genelkim** [comment]
Tests added in https://github.com/genelkim/ulf-sanity-checker/pull/63, and it was already fixed.
