### ISSUE TITLE
Error on until.ps

### ISSUE THREAD

**Issue by vduong143** [genelkim/ulf-sanity-checker#23]
************************************
## Sanity checking formula (before preprocessing).
```
((YOU.PRO ((PRES BE-TO.AUX-V) (STAY.V HERE.ADV-E)))
 (UNTIL.PS (WE.PRO ((PRES COME.V) BACK.ADV-E))))
```

## Sanity checking formula (after preprocessing).
```
(((YOU.PRO ((PRES BE-TO.AUX-V) (STAY.V HERE.ADV-E)))
  (UNTIL.PS (WE.PRO ((PRES COME.V) BACK.ADV-E))))
 NIL NIL)
```

## Possible errors

Possibly failed conditions:
  _"that/tht/whether/ans-to take a single tensed sentence argument."_
Ann segment:
  ```
(UNTIL.PS (WE.PRO ((PRES COME.V) BACK.ADV-E)))
```
Predicted constituent types ((list of types) -- constituent)
  ```
((UNKNOWN) -- UNTIL.PS)
```
  ```
((UNKNOWN) -- (WE.PRO ((PRES COME.V) BACK.ADV-E)))
```

Possibly failed conditions:
  _"UNKNOWN detected in type analysis.  Please ensure this isn't from an annotation error."_
Ann segment:
  ```
NIL
```
Predicted constituent types ((list of types) -- constituent)

## Formula with predicted types (for debugging).

```
(((TYPES UNKNOWN)
  (((TYPES TENSED-SENT)
    (YOU.PRO
     ((TYPES PRED TENSED-VERB)
      (((TYPES TENSED-AUX) (PRES BE-TO.AUX-V))
       ((TYPES VERB PRED) (STAY.V HERE.ADV-E))))))
   ((TYPES UNKNOWN)
    (UNTIL.PS
     ((TYPES UNKNOWN)
      (WE.PRO
       ((TYPES UNKNOWN)
        (((TYPES PRED TENSED-VERB) (PRES COME.V)) BACK.ADV-E)))))))))
```

NIL

####################################

**Comment by genelkim** [comment]
Fixed now, not sure which commit did it (may not be pushed to production yet)
