### ISSUE TITLE
"Rep" is not handled properly

### ISSUE THREAD

**Issue by gplatono** [genelkim/ulf-sanity-checker#28]
Young said the FDA is receiving an average of 10 applications each month requesting permission to begin clinical trials for a new drug ,
the first step in getting the drug approved for prescription use by the public .

(|Young| ((past say.v) 
          (tht 
           ((the.d |FDA|.n) 
            (rep 
             ((pres prog) (receive.v 
                           (an.d (n+preds average.n (of.p (10.d (n+preds (plur application.n) *p)))))
                           (adv-a (= (each.d month.n)))))
             (request.v (k 
                          (n+post permission.n 
                           (to.p-arg (begin.v (k (clinical.a (n+post (plur trial.n) 
                                                              (for.p-arg (a.d (new.a drug.n))) 
                                                              (= (the.d (first.a (n+preds step.n 
                                                                                  (in.p (ka (get.v (the.d drug.n) (approved.a (for.p-arg (k (prescription.n (n+post use.n
                                                                                  (by.p-arg (the.d public.n)))))))))))))))))))))))))))

**Comment by genelkim** [comment]
Handled in https://github.com/genelkim/ulf-sanity-checker/commit/87247c41a7a04dda7df641139910eec72abad733 and 
https://github.com/genelkim/ulf-lib/commit/ce4b20a0b938ba27a27533ecf051817108780f12
will be integrated into next production push
