### ISSUE TITLE
Bug in handling quotes

### ISSUE THREAD

**Issue by vduong143** [genelkim/ulf-sanity-checker#54]
### Sentence: _"They called him " My Lord , " and laughed at all his stories ."_
************************************
## Sanity checking formula (before preprocessing).
```
(THEY.PRO
 (((PAST CALL.V) HIM.PRO (|"| (MY.D LORD.N) |"|)) AND.CC
  ((PAST LAUGH.V) (AT.P-ARG (ALL.D (OF.P (HIS.D STORY.N)))))))
```

## Sanity checking formula (after preprocessing).
```
((THEY.PRO
  (((PAST CALL.V) HIM.PRO (|"| (MY.D LORD.N) |"|)) AND.CC
   ((PAST LAUGH.V) (AT.P-ARG (ALL.D (OF.P (HIS.D STORY.N)))))))
 NIL NIL)
```

## Possible errors

Possibly failed conditions:
  _"Predicate modifications should be scoped into operator-operand pairs."_
Ann segment:
  ```
(|"| (MY.D LORD.N) |"|)
```
Predicted constituent types ((list of types) -- constituent)
  ```
((TERM) -- |"|)
```
  ```
((TERM) -- (MY.D LORD.N))
```
  ```
((TERM) -- |"|)
```

## Formula with predicted types (for debugging).

```
(((TYPES TENSED-SENT)
  (THEY.PRO
   ((TYPES PRED TENSED-VERB)
    (((TYPES PRED TENSED-VERB)
      (((TYPES PRED TENSED-VERB) (PAST CALL.V)) HIM.PRO
       ((TYPES TERM) (|"| ((TYPES TERM) (MY.D LORD.N)) |"|))))
     AND.CC
     ((TYPES PRED TENSED-VERB)
      (((TYPES PRED TENSED-VERB) (PAST LAUGH.V))
       ((TYPES P-ARG)
        (AT.P-ARG
         ((TYPES TERM)
          (ALL.D
           ((TYPES PP PRED) (OF.P ((TYPES TERM) (HIS.D STORY.N)))))))))))))))
```

NIL

####################################

**Comment by genelkim** [comment]
Fixed with https://github.com/genelkim/ulf-lib/commit/2b2214dd9b7e985aa4b2839a633e89fad213cec0. Tests added in https://github.com/genelkim/ulf-sanity-checker/pull/62.
