### ISSUE TITLE
Error on inverted (pres perf) sentence

### ISSUE THREAD

**Issue by bkane2** [genelkim/ulf-sanity-checker#57]
"Have you not learned to respect others?"

`(((pres perf) you.pro not (learn.v (to (respect.v (plur other.n))))) ?)`

## Possible errors

Possibly failed conditions:
  _"auxiliaries take a single untensed verb argument."_
Ann segment:
  ```
((PRES PERF) YOU.PRO (LEARN.V (TO (RESPECT.V (PLUR OTHER.N)))))
```
Predicted constituent types ((list of types) -- constituent)
  ```
((TENSED-AUX) -- (PRES PERF))
```
  ```
((TERM) -- YOU.PRO)
```
  ```
((VERB PRED) -- (LEARN.V (TO (RESPECT.V (PLUR OTHER.N)))))
```

**Comment by genelkim** [comment]
Added this to test and fixed in https://github.com/genelkim/ulf-sanity-checker/pull/63
