### ISSUE TITLE
"rep" doesn't handle this properly: "Let's go, dudes"

### ISSUE THREAD

**Issue by gplatono** [genelkim/ulf-sanity-checker#6]
************************************
Sanity checking formula (before preprocessing).
************************************
((REP (*P ((PRES LET.V) US.PRO GO.V)) (K (PLUR DUDE.N))) !)

************************************
Sanity checking formula (after preprocessing).
************************************
(((REP (*P ((PRES LET.V) US.PRO GO.V)) (K (PLUR DUDE.N))) !) NIL NIL)

************************************
Possible errors
************************************

Possibly failed conditions:
  "Sentence punctuation takes a single tensed sentence argument and is post-fixed."
Ann segment:
  ((REP (*P ((PRES LET.V) US.PRO GO.V)) (K (PLUR DUDE.N))) !)
Predicted constituent types ((list of types) -- constituent)
  ((UNKNOWN) -- (REP (*P ((PRES LET.V) US.PRO GO.V)) (K (PLUR DUDE.N))))
  ((SENT-PUNCT) -- !)

Possibly failed conditions:
  "UNKNOWN detected in type analysis.  Please ensure this isn't from an annotation error."
Ann segment:
  NIL
Predicted constituent types ((list of types) -- constituent)

************************************
Formula with predicted types (for debugging).
************************************
(((TYPES UNKNOWN)
  (((TYPES UNKNOWN)
    (REP
     ((TYPES UNKNOWN)
      (*P
       ((TYPES PRED TENSED-VERB TENSED-SENT)
        (((TYPES PRED TENSED-VERB) (PRES LET.V)) US.PRO GO.V))))
     ((TYPES TERM) (K ((TYPES NOUN PRED) (PLUR DUDE.N))))))
   !))
 NIL NIL)

NIL

####################################

**Comment by genelkim** [comment]
Sid: 229410
************************************
## Sanity checking formula (before preprocessing).
```
((REP (SUB (NP+PREDS WHERE.PRO *P) ((PRES BE.V) YOU.PRO (FROM.P *H)))
  (IN.P |Canada|))
 ?)
```

## Sanity checking formula (after preprocessing).
```
(((REP ((PRES BE.V) YOU.PRO (FROM.P (NP+PREDS WHERE.PRO *P)))
   (IN.P |Canada|))
  ?)
 NIL NIL)
```

## Possible errors

Possibly failed conditions:
  _"Sentence punctuation takes a single tensed sentence argument and is post-fixed."_
Ann segment:
  ```
((REP ((PRES BE.V) YOU.PRO (FROM.P (NP+PREDS WHERE.PRO *P)))
  (IN.P |Canada|))
 ?)
```
Predicted constituent types ((list of types) -- constituent)
  ```
((UNKNOWN) --
 (REP ((PRES BE.V) YOU.PRO (FROM.P (NP+PREDS WHERE.PRO *P)))
  (IN.P |Canada|)))
```
  ```
((SENT-PUNCT) -- ?)
```

Possibly failed conditions:
  _"be.v takes a single predicate argument (unless used after an it-cleft -- ignore this if that's the case)."_
Ann segment:
  ```
((PRES BE.V) YOU.PRO (FROM.P (NP+PREDS WHERE.PRO *P)))
```
Predicted constituent types ((list of types) -- constituent)
  ```
((PRED TENSED-VERB) -- (PRES BE.V))
```
  ```
((TERM) -- YOU.PRO)
```
  ```
((PP PRED) -- (FROM.P (NP+PREDS WHERE.PRO *P)))
```

Possibly failed conditions:
  _"np+preds takes at least 2 arguments where the first is a term and the rest are predicates."_
Ann segment:
  ```
(NP+PREDS WHERE.PRO *P)
```
Predicted constituent types ((list of types) -- constituent)
  ```
((MACRO-SYMBOL) -- NP+PREDS)
```
  ```
((TERM) -- WHERE.PRO)
```
  ```
((UNKNOWN) -- *P)
```

Possibly failed conditions:
  _"UNKNOWN detected in type analysis.  Please ensure this isn't from an annotation error."_
Ann segment:
  ```
NIL
```
Predicted constituent types ((list of types) -- constituent)

## Formula with predicted types (for debugging).

```
(((TYPES UNKNOWN)
  (((TYPES UNKNOWN)
    (REP
     ((TYPES PRED TENSED-VERB)
      (((TYPES PRED TENSED-VERB) (PRES BE.V)) YOU.PRO
       ((TYPES PP PRED)
        (FROM.P ((TYPES TERM) (NP+PREDS WHERE.PRO *P))))))
     ((TYPES PP PRED) (IN.P |Canada|))))
   ?)))
```

NIL

####################################

**Comment by genelkim** [comment]
Handled in 87247c4 and
genelkim/ulf-lib@ce4b20a
will be integrated into next production push
